#!/bin/bash

# GetCollValue v1.0 May 2021 by Edwin Rietmeijer
# Installation of jq is required

d=$(date +%Y.%m.%d)
regex="([0-9]+)\.[0-9]+"
getData() {
  curl -s -X GET https://api.discogs.com/users/EdSpinsRecords/collection/value?token=yourkeyhere --user-agent "ValuePlotter/1.0"
}

cleanup() {
  val=$(echo "${1}" | jq ".${2}" | tr -d \",€)
  if [[ $val =~ $regex ]]
    then
    retval=${BASH_REMATCH[1]}
  fi
  echo $retval
}

data=$(getData)

minimum=$(cleanup "${data}" "minimum")
median=$(cleanup "${data}" "median")
maximum=$(cleanup "${data}" "maximum")

echo ${d} ${minimum} ${median} ${maximum}
