#!/bin/bash

# ValuePlotter v1.0 May 2021 by Edwin Rietmeijer
# Installation of gnuplot and jq is required

if [[ -z ${1} ]]; then
  echo "Usage: $(basename ${0}) [email address]"
  exit 0;
fi

fileRoot="$( cd "$(dirname "$0")" || exit >/dev/null 2>&1 ; pwd -P )"

tmpDirectoryPath="${fileRoot}/tmp"
parsedScriptPath="${tmpDirectoryPath}/collvalue.plt"
graphImagePath="${tmpDirectoryPath}/collectionvalue.png"

dataDirectoryPath="${fileRoot}/data"
collectionValueDataPath="${dataDirectoryPath}/collvalue.dat"
plotScriptTemplatePath="${dataDirectoryPath}/collvalue.tpl"

graphs+=("${graphImagePath}")

mkdir -p ${tmpDirectoryPath}

# Load template into memory
plotScriptTemplate=$(cat ${plotScriptTemplatePath})

# Replace variables in gnuplot script with values and write to file
parsedScript=$(eval "echo \"${plotScriptTemplate}\"")
echo "${parsedScript}" > "${parsedScriptPath}"

# Read latest collection value data
. "${fileRoot}/getcollvalue" >> "${collectionValueDataPath}"

# Render graph
gnuplot "${parsedScriptPath}"

# Mail graph
echo -e "subject:Collection value\n"| (cat - && (for g in ${graphs} ; do uuencode "${g}" $(basename "${g}") ; done )  ) | /usr/sbin/ssmtp "${1}"

# Delete temporary files
if [ -d "${tmpDirectoryPath}" ]; then rm -Rf ${tmpDirectoryPath}; fi
